<a href="https://colab.research.google.com/github/7smn2219/MACHINE-LEARNING/blob/main/Learning/Machine_Learning_with_Python_CookBookipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter	1.	Working	with	Vectors,	Matrices and	Arrays	in	NumPy

## 1.0 Introduction
 NumPy	is	a	foundational	tool	of	the	Python	machine	learning	stack.	NumPy	allows	for	efficient
 operations	on	the	data	structures	often	used	in	machine	learning:	vectors,	matrices,	and	tensors.	While
 NumPy	is	not	the	focus	of	this	book,	it	will	show	up	frequently	throughout	the	following	chapters.	This
 chapter	covers	the	most	common	NumPy	operations	we	are	likely	to	run	into	while	working	on	machine
 learning	workflows

## 1.1 Creating a Vector

### Problem
 You	need	to	create	a	vector.

### Solution
 Use	NumPy	to	create	a	one-dimensional	array:

### Discussion
 NumPy’s	main	data	structure	is	the	multidimensional	array.	A	vector	is	just	an	array	with	a	single
 dimension.	In	order	to	create	a	vector,	we	simply	create	a	one-dimensional	array.	Just	like	vectors,	these
arrays	can	be	represented	horizontally	(i.e.,	rows)	or	vertically	(i.e.,	columns)

In [5]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])
display(vector_row)

# Create a vector as a column
vector_column = np.array([[1], [2], [3]])
display(vector_column)

array([1, 2, 3])

array([[1],
       [2],
       [3]])

##  1.2	Creating	a	Matrix
###Problem
 You	need	to	create	a	matrix.

###Solution
 Use	NumPy	to	create	a	two-dimensional	array:

### Discussion
 To	create	a	matrix	we	can	use	a	NumPy	two-dimensional	array.	In	our	solution,	the	matrix	contains
 three	rows	and	two	columns	(a	column	of	1s	and	a	column	of	2s).
 NumPy	actually	has	a	dedicated	matrix	data	structure

```
matrix_object = np.mat([[1, 2],
                       [1, 2],
                       [1, 2]])
```

In [7]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2], [1,2], [1, 2]])
display(matrix)

array([[1, 2],
       [1, 2],
       [1, 2]])

## 1.3 Creating a Sparse Matrix

### Problem
 Given	data	with	very	few	nonzero	values,	you	want	to	efficiently	represent	it.

### Solution
 Create	a	sparse	matrix

In [11]:
import numpy as np
from scipy import sparse

# Create a matix
matrix = np.array([[0, 0], [0, 1], [3, 0]])

matrix_spare = sparse.csr_matrix(matrix)
display(matrix_spare)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>

### Discussion
  A	frequent	situation	in	machine	learning	is	having	a	huge	amount	of	data;	however,	most	of	the <br>
 elements	in	the	data	are	zeros.	For	example,
 ```
 Imagine	a	matrix	where	the	columns	are	every	movie	on Netflix, the	rows	are	every	Netflix	user,
 and	the	values	are	how	many	times	a	user	has	watched	that particular	movie.
 This	matrix	would	have	tens	of	thousands	of	columns	and	millions	of	rows!
 However,  since	most	users	do	not	watch	most	movies,	the	vast	majority	of
 elements	would	be	zero. A	sparse	matrix	is	a	matrix	in	which	most	elements	are	0.
 ```
 Sparse	matrices	only	store	nonzero	elements <br>
 and	assume	all	other	values	will	be	zero,	leading	to	significant	computational	savings.	In	our	solution, <br>
 we	created	a	NumPy	array	with	two	nonzero	values,	then	converted	it	into	a	sparse	matrix.	If	we	view <br>
 the	sparse	matrix	we	can	see	that	only	the	nonzero	values	are	stored:


In [10]:
print(matrix_spare)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3



 There	are	a	number	of	types	of	sparse	matrices.	However,	in	compressed	sparse	row	(CSR)	matrices, <br>
 (1, 1)	and	(2, 0)	represent	the	(zero-indexed)	indices	of	the	non-zero	values	1	and	3,	respectively. <br>
 For	example,	the	element	1	is	in	the	second	row	and	second	column.	We	can	see	the	advantage	of	sparse <br>
 matrices	if	we	create	a	much	larger	matrix	with	many	more	zero	elements	and	then	compare	this	larger <br>
 matrix	with	our	original	sparse	matrix:


In [14]:
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create a compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


As	we	can	see,	despite	the	fact	that	we	added	many	more	zero	elements	in	the	larger	matrix,	its	sparse \\
 representation	is	exactly	the	same	as	our	original	sparse	matrix.	That	is,	the	addition	of	zero	elements \\
 did	not	change	the	size	of	the	sparse	matrix.
 As	mentioned,	there	are	many	different	types	of	sparse	matrices,	such	as	compressed	sparse	column,	list \\
 of	lists,	and	dictionary	of	keys.	While	an	explanation	of	the	different	types	and	their	implications	is \\
 outside	the	scope	of	this	book,	it	is	worth	noting	that	while	there	is	no	“best”	sparse	matrix	type,	there \\
 are	meaningful	differences	between	them	and	we	should	be	conscious	about	why	we	are	choosing	one \\
 type	over	another

##  1.4	Pre-allocating	Numpy	Arrays
### Problem
 You	need	to	pre-allocate	arrays	of	a	given	size	with	some	value.

### Solution
 NumPy	has	functions	for	generating	vectors	and	matrices	of	any	size	using	0s,	1s,	or	values	of	your
 choice.

In [17]:
import numpy as np

# Generate a vector of shape (1, 5) containing all zeros
vector = np.zeros(shape=5)
display(vector)

# Generate a matrix of shape (3, 3) containing all ones
matrix = np.full(shape=(3, 3), fill_value=1)
display(matrix)

array([0., 0., 0., 0., 0.])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###  Discussion
 Generating	arrays	prefilled	with	data	is	useful	for	a	number	of	purposes,	such	as	making	code	more
 performant	or	having	synthetic	data	to	test	algorithms	with.	In	many	programming	languages,	pre
allocating	an	array	of	default	values	(such	as	0s)	is	considered	common	practice

##  1.5	Selecting	Elements
### Problem
 You	need	to	select	one	or	more	elements	in	a	vector	or	matrix.
### Solution
 NumPy’s	arrays	make	it	easy	to	select	elements	in	vectors	or	matrices

In [20]:
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

display(vector[2])

display(matrix[1, 1])

np.int64(3)

np.int64(5)

### Discussion
 Like	most	things	in	Python,	NumPy	arrays	are	zero-indexed,	meaning	that	the	index	of	the	first	element \\
 is	0,	not	1.	With	that	caveat,	NumPy	offers	a	wide	variety	of	methods	for	selecting	(i.e.,	indexing	and \\
 slicing)	elements	or	groups	of	elements	in	arrays

In [21]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [22]:
vector[:3]

array([1, 2, 3])

In [23]:
vector[-1]

np.int64(6)

In [24]:
vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [25]:
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])