<a href="https://colab.research.google.com/github/7smn2219/MACHINE-LEARNING/blob/main/Learning/Machine_Learning_with_Python_CookBookipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter	1.	Working	with	Vectors,	Matrices and	Arrays	in	NumPy

## 1.0 Introduction
 NumPy	is	a	foundational	tool	of	the	Python	machine	learning	stack.	NumPy	allows	for	efficient \\
 operations	on	the	data	structures	often	used	in	machine	learning:	vectors,	matrices,	and	tensors.	While \\
 NumPy	is	not	the	focus	of	this	book,	it	will	show	up	frequently	throughout	the	following	chapters.	This \\
 chapter	covers	the	most	common	NumPy	operations	we	are	likely	to	run	into	while	working	on	machine \\
 learning	workflows

## 1.1 Creating a Vector

### Problem
 You	need	to	create	a	vector.

### Solution
 Use	NumPy	to	create	a	one-dimensional	array:

### Discussion
 NumPy’s	main	data	structure	is	the	multidimensional	array.	A	vector	is	just	an	array	with	a	single \\
 dimension.	In	order	to	create	a	vector,	we	simply	create	a	one-dimensional	array.	Just	like	vectors,	these \\
arrays	can	be	represented	horizontally	(i.e.,	rows)	or	vertically	(i.e.,	columns)

In [ ]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])
display(vector_row)

# Create a vector as a column
vector_column = np.array([[1], [2], [3]])
display(vector_column)

array([1, 2, 3])

array([[1],
       [2],
       [3]])

##  1.2	Creating	a	Matrix
###Problem
 You	need	to	create	a	matrix.

###Solution
 Use	NumPy	to	create	a	two-dimensional	array:

### Discussion
 To	create	a	matrix	we	can	use	a	NumPy	two-dimensional	array.	In	our	solution,	the	matrix	contains
 three	rows	and	two	columns	(a	column	of	1s	and	a	column	of	2s).
 NumPy	actually	has	a	dedicated	matrix	data	structure

```
matrix_object = np.mat([[1, 2],
                       [1, 2],
                       [1, 2]])
```

In [ ]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2], [1,2], [1, 2]])
display(matrix)

array([[1, 2],
       [1, 2],
       [1, 2]])

## 1.3 Creating a Sparse Matrix

### Problem
 Given	data	with	very	few	nonzero	values,	you	want	to	efficiently	represent	it.

### Solution
 Create	a	sparse	matrix

In [ ]:
import numpy as np
from scipy import sparse

# Create a matix
matrix = np.array([[0, 0], [0, 1], [3, 0]])

matrix_spare = sparse.csr_matrix(matrix)
display(matrix_spare)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>

### Discussion
  A	frequent	situation	in	machine	learning	is	having	a	huge	amount	of	data;	however,	most	of	the <br>
 elements	in	the	data	are	zeros.	For	example,

 ---
 Imagine	a	matrix	where	the	columns	are	every	movie	on Netflix, the	rows	are	every	Netflix	user,
 and	the	values	are	how	many	times	a	user	has	watched	that particular	movie.
 This	matrix	would	have	tens	of	thousands	of	columns	and	millions	of	rows!
 However,  since	most	users	do	not	watch	most	movies,	the	vast	majority	of
 elements	would	be	zero. A	sparse	matrix	is	a	matrix	in	which	most	elements	are	0.

---
 Sparse	matrices	only	store	nonzero	elements <br>
 and	assume	all	other	values	will	be	zero,	leading	to	significant	computational	savings.	In	our	solution, <br>
 we	created	a	NumPy	array	with	two	nonzero	values,	then	converted	it	into	a	sparse	matrix.	If	we	view <br>
 the	sparse	matrix	we	can	see	that	only	the	nonzero	values	are	stored:


In [ ]:
print(matrix_spare)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


 There	are	a	number	of	types	of	sparse	matrices.	However,	in	compressed	sparse	row	(CSR)	matrices, <br>
 (1, 1)	and	(2, 0)	represent	the	(zero-indexed)	indices	of	the	non-zero	values	1	and	3,	respectively. <br>
 For	example,	the	element	1	is	in	the	second	row	and	second	column.	We	can	see	the	advantage	of	sparse <br>
 matrices	if	we	create	a	much	larger	matrix	with	many	more	zero	elements	and	then	compare	this	larger <br>
 matrix	with	our	original	sparse	matrix:


In [ ]:
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create a compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


As	we	can	see,	despite	the	fact	that	we	added	many	more	zero	elements	in	the	larger	matrix,	its	sparse \\
 representation	is	exactly	the	same	as	our	original	sparse	matrix.	That	is,	the	addition	of	zero	elements \\
 did	not	change	the	size	of	the	sparse	matrix.
 As	mentioned,	there	are	many	different	types	of	sparse	matrices,	such	as	compressed	sparse	column,	list \\
 of	lists,	and	dictionary	of	keys.	While	an	explanation	of	the	different	types	and	their	implications	is \\
 outside	the	scope	of	this	book,	it	is	worth	noting	that	while	there	is	no	“best”	sparse	matrix	type,	there \\
 are	meaningful	differences	between	them	and	we	should	be	conscious	about	why	we	are	choosing	one \\
 type	over	another

##  1.4	Pre-allocating	Numpy	Arrays
### Problem
 You	need	to	pre-allocate	arrays	of	a	given	size	with	some	value.

### Solution
 NumPy	has	functions	for	generating	vectors	and	matrices	of	any	size	using	0s,	1s,	or	values	of	your
 choice.

In [ ]:
import numpy as np

# Generate a vector of shape (1, 5) containing all zeros
vector = np.zeros(shape=5)
display(vector)

# Generate a matrix of shape (3, 3) containing all ones
matrix = np.full(shape=(3, 3), fill_value=1)
display(matrix)

array([0., 0., 0., 0., 0.])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###  Discussion
 Generating	arrays	prefilled	with	data	is	useful	for	a	number	of	purposes,	such	as	making	code	more
 performant	or	having	synthetic	data	to	test	algorithms	with.	In	many	programming	languages,	pre
allocating	an	array	of	default	values	(such	as	0s)	is	considered	common	practice

##  1.5	Selecting	Elements
### Problem
 You	need	to	select	one	or	more	elements	in	a	vector	or	matrix.
### Solution
 NumPy’s	arrays	make	it	easy	to	select	elements	in	vectors	or	matrices

In [ ]:
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

display(vector[2])

display(matrix[1, 1])

np.int64(3)

np.int64(5)

### Discussion
 Like	most	things	in	Python,	NumPy	arrays	are	zero-indexed,	meaning	that	the	index	of	the	first	element \\
 is	0,	not	1.	With	that	caveat,	NumPy	offers	a	wide	variety	of	methods	for	selecting	(i.e.,	indexing	and \\
 slicing)	elements	or	groups	of	elements	in	arrays

In [ ]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [ ]:
vector[:3]

array([1, 2, 3])

In [ ]:
vector[-1]

np.int64(6)

In [ ]:
vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [ ]:
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

##  1.6	Describing	a	Matrix
### Problem
 You	want	to	describe	the	shape,	size,	and	dimensions	of	the	matrix.
### Solution
 Use	the	shape,	size,	and	ndim	attributes	of	a	NumPy	object:

In [27]:
matrix.shape

(3, 3)

In [28]:
matrix.size

9

In [29]:
matrix.ndim

2

### Discussion
 This	might	seem	basic	(and	it	is);	however,	time	and	again	it	will	be	valuable	to	check	the	shape	and
 size	of	an	array	both	for	further	calculations	and	simply	as	a	gut	check	after	some	operation

## 1.7	Applying	Functions	Over	Each	Element
### Problem
 You	want	to	apply	some	function	to	all	elements	in	an	array.
### Solution
 Use	NumPy's	vectorize	method:

In [30]:
# Create matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

###  Discussion
 NumPy’s	vectorize	class	converts	a	function	into	a	function	that	can	apply	to	all	elements	in	an	array
 or	slice	of	an	array.	It’s	worth	noting	that	vectorize	is	essentially	a	for	loop	over	the	elements	and
 does	not	increase	performance.	Furthermore,	NumPy	arrays	allow	us	to	perform	operations	between
 arrays	even	if	their	dimensions	are	not	the	same	(a	process	called	broadcasting).	For	example,	we	can
create	a	much	simpler	version	of	our	solution	using	broadcasting

In [31]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 1.8	Finding	the	Maximum	and	Minimum	Values
### Problem
 You	need	to	find	the	maximum	or	minimum	value	in	an	array.
### Solution
 Use	NumPy’s	max	and	min	methods

In [47]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

display(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# Returne maximum element
np.max(matrix)

np.int64(9)

In [49]:
# Return minimum element
np.min(matrix)

np.int64(1)

###  Discussion
 Often	we	want	to	know	the	maximum	and	minimum	value	in	an	array	or	subset	of	an	array.	This	can	be
 accomplished	with	the	max	and	min	methods.	Using	the	axis	parameter	we	can	also	apply	the	operation
 along	a	certain	axis

In [50]:
# Find maximum element in dach column
np.max(matrix, axis=0)

array([7, 8, 9])

In [51]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

## 1.9	Calculating	the	Average,	Variance,	and	Standard	Deviation
### Problem
 You	want	to	calculate	some	descriptive	statistics	about	an	array.
### Solution
 Use	NumPy's	mean,	var,	and	std

In [52]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [56]:
# Return mean
np.mean(matrix)

np.float64(5.0)

In [57]:
# Return var
np.var(matrix)

np.float64(6.666666666666667)

In [58]:
# Return std
np.std(matrix)

np.float64(2.581988897471611)

###  Discussion
 Just	like	with	max	and	min,	we	can	easily	get	descriptive	statistics	about	the	whole	matrix	or	do
 calculations	along	a	single	axis:

In [59]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

##  1.10	Reshaping	Arrays
### Problem
 You	want	to	change	the	shape	(number	of	rows	and	columns)	of	an	array	without	changing	the	element
 values

### Solution
 Use	NumPy’s	reshape

In [60]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Discussion
 reshape	allows	us	to	restructure	an	array	so	that	we	maintain	the	same	data	but	it	is	organized	as	a
 different	number	of	rows	and	columns.	The	only	requirement	is	that	the	shape	of	the	original	and	new
 matrix	contain	the	same	number	of	elements	(i.e.,	the	same	size).	We	can	see	the	size	of	a	matrix	using
 size:

In [61]:
matrix.size

12

 One	useful	argument	in	reshape	is	-1,	which	effectively	means	“as	many	as	needed,”	so	reshape(1,-1)	means	one	row	and	as	many	columns	as	needed:

In [62]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Finally,	if	we	provide	one	integer,	reshape	will	return	a	1D	array	of	that	length

In [63]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 1.11	Transposing	a	Vector	or	Matrix
 ### Problem
 You	need	to	transpose	a	vector	or	matrix.
 ### Solution
 Use	the	T	method

In [65]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

###  Discussion
 Transposing	is	a	common	operation	in	linear	algebra	where	the	column	and	row	indices	of	each	element
 are	swapped.	One	nuanced	point	that	is	typically	overlooked	outside	of	a	linear	algebra	class	is	that,
 technically,	a	vector	cannot	be	transposed	because	it	is	just	a	collection	of	values

In [70]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

 However,	it	is	common	to	refer	to	transposing	a	vector	as	converting	a	row	vector	to	a	column	vector
 (notice	the	second	pair	of	brackets)	or	vice	versa:

In [71]:
# Transpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 1.12	Flattening	a	Matrix
### Problem
 You	need	to	transform	a	matrix	into	a	one-dimensional	array.
### Solution
 Use	flatten:

In [72]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Discussion
 flatten	is	a	simple	method	to	transform	a	matrix	into	a	one-dimensional	array.	Alternatively,	we	can
 use	reshape	to	create	a	row	vector

In [73]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

One	more	common	method	to	flatten	arrays	is	the	ravel	method.	Unlike	flatten	which	returns	a	copy
 of	the	original	array,	ravel	operates	on	the	original	object	itself	and	is	therefore	slightly	faster.	It	also
 lets	us	flatten	lists	of	arrays,	which	we	can’t	do	with	the	flatten	method.	This	operation	is	useful	for
 flattening	very	large	arrays	and	speeding	up	code.

In [75]:
# Create one matrix
matrix_a = np.array([[1, 2], [3, 4]])

# Create a second matrix
matrix_b = np.array([[5, 6], [7, 8]])

# Create a list of matrics
matrix_list = [matrix_a, matrix_b]

matrix_list

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [76]:
# Flatten the entire list of matrices
np.ravel(matrix_list)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Will remove later when chapter completes

---

# Topic 2